"""
Documentation Generator Service
================================

Generates a human-readable Markdown deployment guide from a DeployPayload.

This document is designed to be handed to a customer so they can:
1. Understand what was designed for them
2. Follow step-by-step deployment instructions
3. Reference the permission matrix for each team

LESSON: String building with f-strings and list comprehensions
======================================================
We build the document section by section, collecting strings in a list
then joining at the end. This is more efficient than concatenating strings
one by one (each += creates a new string object in memory).
"""

from datetime import datetime
from typing import List

from services.payload_builder import DeployPayload


def generate_deployment_guide(payload: DeployPayload, project_key: str) -> str:
    """
    Generate a Markdown deployment guide from a DeployPayload.

    Args:
        payload: The built DeployPayload containing roles and teams
        project_key: The LaunchDarkly project key

    Returns:
        A Markdown string ready to download as a .md file
    """
    sections = []

    sections.append(_header(payload, project_key))
    sections.append(_deployment_instructions())
    sections.append(_roles_section(payload))
    sections.append(_teams_section(payload))
    sections.append(_permission_matrix(payload))
    sections.append(_footer())

    return "\n\n".join(sections)


# =============================================================================
# Section builders
# =============================================================================

def _header(payload: DeployPayload, project_key: str) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    role_count = payload.get_role_count()
    team_count = payload.get_team_count()

    return f"""# LaunchDarkly RBAC Deployment Guide

| Field | Value |
|-------|-------|
| **Customer** | {payload.customer_name} |
| **Project** | `{project_key}` |
| **Generated** | {generated_at} |
| **Custom Roles** | {role_count} |
| **Teams** | {team_count} |

---

> This document was generated by the RBAC Builder.
> Share it with your LaunchDarkly administrator along with the JSON payload file."""


def _deployment_instructions() -> str:
    return """## Deployment Instructions

### Prerequisites

- LaunchDarkly account with **Admin** or **Owner** role
- Access to **Organization Settings → Roles** and **Organization Settings → Teams**
- **Python 3.8 or higher** — check with `python --version` or `python3 --version`
- The `requests` library — installed via pip (see Step 1 below)

### Deployment Order

> ⚠️ **Important:** Custom roles must be created BEFORE teams. Teams reference role keys that must already exist.

**Step 0 — Set up Python environment**

```bash
# Verify Python version (3.8+ required)
python --version        # or: python3 --version

# Create a virtual environment (recommended — keeps dependencies isolated)
python3 -m venv venv
source venv/bin/activate    # macOS / Linux
# venv\\Scripts\\activate   # Windows

# Install the only dependency
pip install requests
```

**Step 1 — Create Custom Roles**

For each role in the JSON payload (`custom_roles` array):
1. Go to **Organization Settings → Roles → Create Role**
2. Set the **Key** exactly as shown (e.g. `create-flags`)
3. Set the **Name** as shown
4. Under **Advanced → Scope using attribute key**, add the `projects` attribute
5. Add each policy statement from the JSON

**Step 2 — Create Teams**

For each team in the JSON payload (`teams` array):
1. Go to **Organization Settings → Teams → Create Team**
2. Set the **Key** and **Name** as shown
3. Add the **Custom Roles** listed in `customRoleKeys`
4. Add each **Role Attribute** from `roleAttributes`

**Step 3 — Assign Members**

Assign team members via:
- Manual assignment in the LD UI
- SSO/SCIM provisioning (recommended for enterprise)

### Using the API

LaunchDarkly has no bulk import endpoint. Each role and team must be a **separate API call**.
Extract each object from the JSON arrays and POST individually.

**Create each custom role** (repeat for every entry in `custom_roles`):
```bash
curl -X POST https://app.launchdarkly.com/api/v2/roles \\
  -H "Authorization: YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "key": "create-flags",
    "name": "Create Flags",
    "base_permissions": "no_access",
    "policy": [...]
  }'
```

**Create each team** (repeat for every entry in `teams`, only after all roles exist):
```bash
curl -X POST https://app.launchdarkly.com/api/v2/teams \\
  -H "Authorization: YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "key": "voya-web-dev",
    "name": "Voya Web: Developer",
    "customRoleKeys": [...],
    "roleAttributes": [...]
  }'
```

> **Note:** The JSON payload file also contains `metadata` and `deployment_order` fields — these are for reference only and should not be included in API calls.

---"""


def _roles_section(payload: DeployPayload) -> str:
    lines = ["## Custom Roles\n"]
    lines.append(f"Total: **{payload.get_role_count()} roles** — create these first.\n")

    for role in payload.roles:
        lines.append(f"### `{role['key']}` — {role['name']}\n")

        if role.get("description"):
            lines.append(f"{role['description']}\n")

        lines.append("**Policy statements:**\n")
        for i, stmt in enumerate(role.get("policy", []), 1):
            effect = stmt.get("effect", "allow").upper()
            actions = stmt.get("actions", [])
            resources = stmt.get("resources", [])

            lines.append(f"*Statement {i}* — `{effect}`")
            lines.append(f"- Resource: `{resources[0] if resources else 'n/a'}`")
            lines.append(f"- Actions: {', '.join(f'`{a}`' for a in actions)}")
            lines.append("")

        lines.append("---")

    return "\n".join(lines)


def _teams_section(payload: DeployPayload) -> str:
    lines = ["## Teams\n"]
    lines.append(f"Total: **{payload.get_team_count()} teams** — create after all custom roles exist.\n")

    for team in payload.teams:
        lines.append(f"### `{team['key']}` — {team['name']}\n")

        if team.get("description"):
            lines.append(f"{team['description']}\n")

        # Role attribute values
        role_attrs = {a["key"]: a["values"] for a in team.get("roleAttributes", [])}
        projects = role_attrs.get("projects", [])
        if projects:
            lines.append(f"**Project access:** `{'`, `'.join(projects)}`\n")

        # Custom roles assigned
        role_keys = team.get("customRoleKeys", [])
        if role_keys:
            lines.append("**Assigned roles:**\n")
            for key in sorted(role_keys):
                lines.append(f"- `{key}`")
            lines.append("")

        # Environment scoping per role
        env_attrs = {k: v for k, v in role_attrs.items() if k.endswith("-environments")}
        if env_attrs:
            lines.append("**Environment access per permission:**\n")
            lines.append("| Permission | Environments |")
            lines.append("|------------|-------------|")
            for attr_key, envs in sorted(env_attrs.items()):
                # Convert "update-targeting-environments" → "Update Targeting"
                perm_name = attr_key.replace("-environments", "").replace("-", " ").title()
                lines.append(f"| {perm_name} | {', '.join(f'`{e}`' for e in envs)} |")
            lines.append("")

        lines.append("---")

    return "\n".join(lines)


def _permission_matrix(payload: DeployPayload) -> str:
    """Build a summary matrix: team rows × permission columns."""
    if not payload.teams:
        return ""

    lines = ["## Permission Matrix Summary\n"]
    lines.append("Quick reference: which teams have which permissions and in which environments.\n")

    for team in payload.teams:
        lines.append(f"### {team['name']}\n")

        role_attrs = {a["key"]: a["values"] for a in team.get("roleAttributes", [])}
        projects = role_attrs.get("projects", [])
        env_attrs = {k: v for k, v in role_attrs.items() if k.endswith("-environments")}
        role_keys = set(team.get("customRoleKeys", []))

        # Project-level roles (no env scoping)
        project_roles = [k for k in sorted(role_keys) if not any(
            k == rk for rk in role_keys
            if any(k in role_attrs for role_attrs in [env_attrs])
        )]

        if projects:
            lines.append(f"**Project:** `{'`, `'.join(projects)}`")

        if env_attrs:
            lines.append("\n**Environment-scoped permissions:**\n")
            lines.append("| Permission | Environments |")
            lines.append("|------------|-------------|")
            for attr_key, envs in sorted(env_attrs.items()):
                perm_name = attr_key.replace("-environments", "").replace("-", " ").title()
                lines.append(f"| {perm_name} | {', '.join(envs)} |")
        lines.append("")

    return "\n".join(lines)


def _footer() -> str:
    return """---

## Reference

| Resource | Link |
|----------|------|
| Custom Roles | https://docs.launchdarkly.com/home/account/custom-roles |
| Teams | https://docs.launchdarkly.com/home/account/teams |
| Role Attributes | https://docs.launchdarkly.com/home/account/role-attributes |
| Policies | https://docs.launchdarkly.com/home/account/role-policies |

---

*Generated by RBAC Builder — LaunchDarkly Professional Services*"""
